digicard.ui/Controllers/CardsController.cs
using System.Threading.Tasks;
namespace digicard.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Options;
    using Newtonsoft.Json;
    using digicard.Components;
    using digicard.Components.API;
    using digicard.Components.Shared.API;
    using digicard.Components.UI;
    using digicard.Components.UI.Accounts;
    using digicard.Components.UI.Cards;
    using digicard.Components.UI.Users;
    using digicard.Components.UI.Authentication;
    using digicard.Mappers;
    using digicard.Models.API.Request.Users;
    using digicard.Models.API.Request.Cards;
    using digicard.Models.API.Response.Cards;
    using digicard.Models.UI.View.Accounts;
    using digicard.Models.UI.Page;
    using digicard.Models.UI.Page.Authentication;
    using digicard.Models.UI.Page.Accounts;
    using digicard.Models.UI.Page.Cards;
    using digicard.Models.UI.View.Cards;

    [Authorize]
    public class CardsController : DigicardUIController
    {
        public CardsController(IWebHostEnvironment environment, IOptions<AppSettings> appSettings, IServiceProvider serviceProvider)
            : base(environment, appSettings, serviceProvider)
        {
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            CardsIndexPageModel model = new CardsIndexPageModel();
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> New()
        {
            CardsNewPageModel model = new CardsNewPageModel();
            
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> New(CardsNewPageModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    APIResult result = await CardsAPIContext.Current.Create(new CreateCardRequestModel()
                    {
                        NameOnCard = model.NewCard.NameOnCard,
                        Description = model.NewCard.Description,
                        Landline = model.NewCard.Landline,
                        Mobile = model.NewCard.Mobile,
                        Email = model.NewCard.Email,
                        Facebook = model.NewCard.Facebook,
                        Twitter = model.NewCard.Twitter,
                        Instagram = model.NewCard.Instagram,
                        Domain = model.NewCard.Domain,
                        AddressLine1 = model.NewCard.AddressLine1,
                        AddressLine2 = model.NewCard.AddressLine2,
                        AddressLine3 = model.NewCard.AddressLine3,
                        PostCode = model.NewCard.PostCode,
                        Country = model.NewCard.Country
                    });

                    if (result.Success)
                    {
                        // get objects
                        CardResponseModel response = JsonConvert.DeserializeObject<CardResponseModel>(Convert.ToString(result.Data));
                        model.NewCard = CardsMapper.MapCardResponseModelToCardViewModel(response);

                        return RedirectToAction("Index");
                    }
                    else
                    {
                        model.ErrorMessages.AddRange(result.Errors.Select(e => e.FriendlyMessage));
                    }
                }
                catch (Exception ex)
                {
                    await this.Log.WriteSystemLog(ex);
                    model.ErrorMessages.Add(ex.Message);
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            CardsEditPageModel model = new CardsEditPageModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CardsEditPageModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    APIResult result = await CardsAPIContext.Current.Create(new CreateCardRequestModel()
                    {
                        // TODO: Add Fields
                        // BusinessName = model.NewCard.BusinessName,
                    });

                    if (result.Success)
                    {
                        // get objects
                        CardResponseModel response = JsonConvert.DeserializeObject<CardResponseModel>(Convert.ToString(result.Data));
                        model.Card = CardsMapper.MapCardResponseModelToCardViewModel(response);

                        return RedirectToAction("Index");
                    }
                    else
                    {
                        model.ErrorMessages.AddRange(result.Errors.Select(e => e.FriendlyMessage));
                    }
                }
                catch (Exception ex)
                {
                    await this.Log.WriteSystemLog(ex);
                    model.ErrorMessages.Add(ex.Message);
                }
            }

            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(string id)
        {
            CardsDetailPageModel model = new CardsDetailPageModel();

            // TODO: if published or it's your card
            // TODO: IF not logged in show full page version
            model.Card = new CardViewModel()
            {
                NameOnCard = "Card 1"
            };

            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
//        [Route("/cards/magicrouter/{key}")]
        public async Task<IActionResult> MagicRouter(string id)
        {
            CardsDetailPageModel model = new CardsDetailPageModel();

            APIResult result = await CardsAPIContext.Current.GetBySlug(id.ToLower());

            if(result.Success)
            {
                CardResponseModel response = JsonConvert.DeserializeObject<CardResponseModel>(Convert.ToString(result.Data));
                model.Card = CardsMapper.MapCardResponseModelToCardViewModel(response);
            }

            return View("Details", model);
        }
    }
}

digicard.ui/Views/Cards/Details.cshtml
@using digicard.Models.UI.Page.Cards
@model CardsDetailPageModel
@{
    if(!User.Identity.IsAuthenticated)
    {
        Layout = "/Views/Shared/_CardLayout.cshtml";
    }
}

@if(Model.Card == null || Model.Card.CardId == 0)
{
    <p class="alert alert-danger">NOPE GO AWAY</p>
}
else
{
    <div class="card-thumbnail card-skin-1">
        <h2>@Model.Card.NameOnCard</h2>
        <p>
            T: <span>@Model.Card.Landline</span>
        </p>
        <p>
            M: <span>@Model.Card.Landline</span>
        </p>
        <p>
            E: <span>@Model.Card.Email</span>
        </p>
        <p>
            Facebook: <span>@Model.Card.Facebook</span>
        </p>
        <p>
            Twitter: <span>@Model.Card.Twitter</span>
        </p>
        <p>
            Instagram: <span>@Model.Card.Instagram</span>
        </p>
        <p>
            @Model.Card.AddressLine1
            @Model.Card.AddressLine2
            @Model.Card.AddressLine3
            @Model.Card.PostCode
            @Model.Card.Country
        </p>
    </div>
}

digicard.ui/Views/Cards/Edit.cshtml
CARDS EDIT

digicard.ui/Views/Cards/Index.cshtml
@using digicard.Models.UI.Page.Cards
@using digicard.Models.UI.View.Cards
@model CardsIndexPageModel
@{
    ViewBag.Title = "Your Cards";
}

@if(Model.Cards.Any())
{ 
    <h2>Your Cards</h2>   
    @foreach(CardViewModel card in Model.Cards)
    {
        <partial name="/Views/Cards/_Thumbnail.cshtml" model="card" />
        <div class="card-actions">
            <a class="btn btn-primary" asp-action="Edit" asp-route-id="@card.CardId">Edit</a>
            <a class="btn btn-secondary" asp-action="Details" asp-route-id="@card.CardId">View</a>
            @if(card.IsPublished)
            {
                <span class="alert alert-success">Published</span>
            }
            else
            {
                <span class="alert alert-warning">Not published!</span>
            }
        </div>
    }
}
else
{
    <p class="alert alert-info">
        You don't have any cards yet. <a asp-controller="Cards" asp-action="New" class="btn btn-primary">Create one now</a>
    </p>
}

digicard.ui/Views/Cards/New.cshtml
@using digicard.Models.UI.Page.Cards
@model CardsNewPageModel

<div class="container">
    <h2 class="mt-4 text-center">Create a New Card</h2>

    <div class='row m-0'>
        @await Html.PartialAsync("~/Views/Shared/_Errors.cshtml", Model)
        @await Html.PartialAsync("~/Views/Shared/_Alerts.cshtml", Model)
    </div>

	<form asp-controller="Cards" asp-action="New" asp-method="Post" class="p-3 mt-3">
        <h3 class="">Card Details</h3>
        <div class="row border-top">
            <div class="col-12 mt-3 form-group">
                <label asp-for="NewCard.NameOnCard">Name</label>
                <input type="text" asp-for="NewCard.NameOnCard" class="form-control" />
                @Html.ValidationMessageFor(m => m.NewCard.NameOnCard, "", new { @class = "text-danger" })
            </div>

            <div class="col-12 mt-3 form-group">
                <label asp-for="NewCard.Description">Description</label>
                <textarea asp-for="NewCard.Description" class="form-control"></textarea>
                @Html.ValidationMessageFor(m => m.NewCard.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <h3 class="mt-5">Contact Details</h3>
        <div class="row border-top">
            <div class="col-12 col-md-6 mt-3 form-group">
                <label asp-for="NewCard.Mobile">Mobile</label>
                <input type="text" asp-for="NewCard.Mobile" class="form-control" />
                @Html.ValidationMessageFor(m => m.NewCard.Mobile, "", new { @class = "text-danger" })
            </div>

            <div class="col-12 col-md-6 mt-3 form-group">
                <label asp-for="NewCard.Landline">Landline</label>
                <input type="text" asp-for="NewCard.Landline" class="form-control" />
                @Html.ValidationMessageFor(m => m.NewCard.Landline, "", new { @class = "text-danger" })
            </div>

            <div class="col-12 col-md-6 mt-3 form-group">
                <label asp-for="NewCard.Email">Email</label>
                <input type="email" asp-for="NewCard.Email" class="form-control" />
                @Html.ValidationMessageFor(m => m.NewCard.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <h3 class="mt-5">Address Details</h3>
        <div class="row border-top">
            <div class="col-12 col-md-6 mt-3 form-group">
                <label asp-for="NewCard.AddressLine1">AddressLine1</label>
                <input type="text" asp-for="NewCard.AddressLine1" class="form-control" />
                @Html.ValidationMessageFor(m => m.NewCard.AddressLine1, "", new { @class = "text-danger" })
            </div>

            <div class="col-12 col-md-6 mt-3 form-group">
                <label asp-for="NewCard.AddressLine2">AddressLine2</label>
                <input type="text" asp-for="NewCard.AddressLine2" class="form-control" />
                @Html.ValidationMessageFor(m => m.NewCard.AddressLine2, "", new { @class = "text-danger" })
            </div>

            <div class="col-12 col-md-6 mt-3 form-group">
                <label asp-for="NewCard.AddressLine3">AddressLine3</label>
                <input type="text" asp-for="NewCard.AddressLine3" class="form-control" />
                @Html.ValidationMessageFor(m => m.NewCard.AddressLine3, "", new { @class = "text-danger" })
            </div>

            <div class="col-12 col-md-6 mt-3 form-group">
                <label asp-for="NewCard.PostCode">PostCode</label>
                <input type="text" asp-for="NewCard.PostCode" class="form-control" />
                @Html.ValidationMessageFor(m => m.NewCard.PostCode, "", new { @class = "text-danger" })
            </div>

            <div class="col-12 col-md-6 mt-3 form-group">
                <label asp-for="NewCard.Country">Country</label>
                <input type="text" asp-for="NewCard.Country" class="form-control" />
                @Html.ValidationMessageFor(m => m.NewCard.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <h3 class="mt-5">Social Media</h3>
        <div class="row border-top">
            <div class="col-12 col-md-6 mt-3 form-group">
                <label asp-for="NewCard.Facebook">Facebook</label>
                <input type="text" asp-for="NewCard.Facebook" class="form-control" />
                @Html.ValidationMessageFor(m => m.NewCard.Facebook, "", new { @class = "text-danger" })
            </div>

            <div class="col-12 col-md-6 mt-3 form-group">
                <label asp-for="NewCard.Twitter">Twitter</label>
                <input type="text" asp-for="NewCard.Twitter" class="form-control" />
                @Html.ValidationMessageFor(m => m.NewCard.Twitter, "", new { @class = "text-danger" })
            </div>

            <div class="col-12 col-md-6 mt-3 form-group">
                <label asp-for="NewCard.Instagram">Instagram</label>
                <input type="text" asp-for="NewCard.Instagram" class="form-control" />
                @Html.ValidationMessageFor(m => m.NewCard.Instagram, "", new { @class = "text-danger" })
            </div>
        </div>

        <h3 class="mt-5">Custom Domain</h3>
        <div class="row border-top">
            <div class="col-12 col-md-6 mt-3 form-group">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            </div>

            <div class="col-12 col-md-6 mt-3 form-group">
                <label asp-for="NewCard.Domain">Domain</label>
                <input type="text" asp-for="NewCard.Domain" class="form-control" />
                @Html.ValidationMessageFor(m => m.NewCard.Domain, "", new { @class = "text-danger" })
            </div>
        </div>

        <h3 class="mt-5">Publish</h3>
        <div class="row border-top">
            <div class="col-12 col-md-6 mt-3 form-group">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            </div>


            <div class="col-12 col-md-6 mt-3 custom-control custom-switch">
                <input type="checkbox" class="custom-control-input" asp-for="NewCard.IsPublished">
                <label class="custom-control-label" asp-for="NewCard.IsPublished">Publish Now</label>
            </div>
        </div>

		<div class="form-row d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
</div>

digicard.ui/Views/Cards/_Thumbnail.cshtml
@using digicard.Models.UI.View.Cards
@model CardViewModel

<div class="card-thumbnail card-skin-1">
    <h2>@Model.NameOnCard</h2>
    <p>
        T: <span>@Model.Landline</span>
    </p>
    <p>
        M: <span>@Model.Landline</span>
    </p>
    <p>
        E: <span>@Model.Email</span>
    </p>
    <p>
        Facebook: <span>@Model.Facebook</span>
    </p>
    <p>
        Twitter: <span>@Model.Twitter</span>
    </p>
    <p>
        Instagram: <span>@Model.Instagram</span>
    </p>
    <p>
        @Model.AddressLine1
        @Model.AddressLine2
        @Model.AddressLine3
        @Model.PostCode
        @Model.Country
    </p>
    <p>
        <a asp-controller="Cards" asp-action="Details" asp-route-id="@Model.CardId">View full details &raquo;</a>
    </p>
</div>