digicard.ui/Controllers/AuthenticationController.cs
using System.Net;
namespace digicard.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Options;
    using digicard.Components;
    using digicard.Components.API;
    using digicard.Components.API.Authentication;
    using digicard.Components.UI;
    using digicard.Components.UI.Authentication;
    using digicard.Components.Shared.API;
    using digicard.Models.API.Request.Accounts;
    using digicard.Models.API.Request.Users;
    using digicard.Models.UI.Page.Authentication;
    using digicard.Models.UI.View.Users;

    public class AuthenticationController : DigicardUIController
    {
        public AuthenticationController(IWebHostEnvironment environment, IOptions<AppSettings> appSettings, IServiceProvider serviceProvider)
            : base(environment, appSettings, serviceProvider)
        {
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                return await RedirectToHomepage();
            }

            LoginPageModel model = new LoginPageModel();

            if (HttpContext.Request.Query.Any(q => q.Key.ToLower() == "returnurl"))
            {
                model.ReturnUrl = HttpContext.Request.Query.First(q => q.Key.ToLower() == "returnurl").Value;
            }

            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginPageModel model)
        {
            if (User.Identity.IsAuthenticated)
            {
                return await RedirectToHomepage(returnUrl: model.ReturnUrl);
            }

            if (ModelState.IsValid)
            {
                try
                {
                    UserViewModel user = await AuthenticationManager.Current.SignIn(model.EmailAddress, model.Password, Request.HttpContext.Connection.RemoteIpAddress.ToString());

                    if (user != null && user.IsAuthenticated)
                    {
                        return await RedirectToHomepage(returnUrl: model.ReturnUrl, activeUser: user);
                    }

                    model.ErrorMessages.Add("Email or Password incorrect.");
                }
                catch (Exception ex)
                {
                    await this.Log.WriteSystemLog(ex);
                    model.ErrorMessages.Add(ex.Message);
                }
            }

            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Logout()
        {
            if (User.Identity.IsAuthenticated)
            {
                await AuthenticationManager.Current.SignOut();
            }

            return this.Redirect("/Authentication/Login");
        }

        [HttpGet]
        [Route("/register")]
        [AllowAnonymous]
        public async Task<IActionResult> Register()
        {
            if (User.Identity.IsAuthenticated)
            {
                return await RedirectToHomepage();
            }

            RegisterPageModel model = new RegisterPageModel();

            if (HttpContext.Request.Query.Any(q => q.Key.ToLower() == "returnurl"))
            {
                model.ReturnUrl = HttpContext.Request.Query.First(q => q.Key.ToLower() == "returnurl").Value;
            }

            return View(model);
        }

        [HttpPost]
        [Route("/register")]
        [AllowAnonymous]
        public async Task<IActionResult> Register(RegisterPageModel model)
        {
            if (this.User.Identity.IsAuthenticated)
            {
                return await this.RedirectToHomepage(returnUrl: model.ReturnUrl);
            }

            if (this.ModelState.IsValid)
            {
                try
                {
                    UserViewModel user = await AuthenticationManager.Current.Register(model.EmailAddress, model.Password);

                    if (user != null)
                    {
                        user = await AuthenticationManager.Current.SignIn(model.EmailAddress, model.Password, Request.HttpContext.Connection.RemoteIpAddress.ToString());

                        if (user != null && user.IsAuthenticated)
                        {
                            return await this.RedirectToHomepage(model.ReturnUrl);
                        }
                    }
                    else
                    {
                        model.ErrorMessages.Add("There was an error creating your account.");
                    }
                }
                catch (Exception ex)
                {
                    await this.Log.WriteSystemLog(ex);
                    model.ErrorMessages.Add(ex.Message);
                }
            }

            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> StartPasswordReset()
        {
            if (this.User.Identity.IsAuthenticated)
            {
                return await this.RedirectToHomepage();
            }

            StartPasswordResetPageModel model = new StartPasswordResetPageModel();

            return this.View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> StartPasswordReset(StartPasswordResetPageModel model)
        {
            if (this.User.Identity.IsAuthenticated)
            {
                return await this.RedirectToHomepage();
            }

            if (this.ModelState.IsValid)
            {
                try
                {
                    APIResult result = await AuthenticationManager.Current.StartPasswordReset(model.EmailAddress);

                    if (result.Errors.Any())
                    {
                        model.ErrorMessages.AddRange(result.Errors.Select(t => t.FriendlyMessage).ToList());
                    }
                    else
                    {
                        model.AlertMessages.Add("A password reset email was sent.");
                    }
                }
                catch (Exception ex)
                {
                    await this.Log.WriteSystemLog(ex);
                    model.ErrorMessages.Add($"Failed to reset your password. Sorry! Please let us know and quote this error: {ex.Message}.");
                }
            }

            return this.View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult FinishPasswordReset(string id)
        {
            FinishPasswordResetPageModel model = new FinishPasswordResetPageModel
            {
                Token = id
            };

            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> FinishPasswordReset(FinishPasswordResetPageModel model)
        {
            if (this.User.Identity.IsAuthenticated)
            {
                return await this.RedirectToHomepage();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    FinishPasswordResetRequestModel requestModel = new FinishPasswordResetRequestModel()
                    {
                        Password = model.Password
                    };

                    APIResult result = await AuthenticationManager.Current.FinishPasswordReset(model.Token, requestModel);

                    if (result.Success)
                    {
                        model.ResetFinished = true;
                    }
                    else
                    {
                        model.ErrorMessages.AddRange(result.Errors.Select(e => e.FriendlyMessage));
                    }
                }
                catch (Exception ex)
                {
                    await this.Log.WriteSystemLog(ex);
                    model.ErrorMessages.Add($"Failed to reset your password. Sorry! Please let us know and quote this error: {ex.Message}.");
                }
            }

            return View(model);
        }

        private async Task<IActionResult> RedirectToHomepage(string returnUrl = null, UserViewModel activeUser = null)
        {
            UserViewModel current = activeUser == null ? await AuthenticationManager.Current.GetCurrentUser() : activeUser;

            if (current != null && current.IsAuthenticated)
            {
                if (!string.IsNullOrEmpty(returnUrl))
                {
                    return this.Redirect(returnUrl);
                }

                if (this.HttpContext.Request.Query.Any(q => q.Key.ToLower() == "returnurl"))
                {
                    return this.Redirect(this.HttpContext.Request.Query.First(q => q.Key.ToLower() == "returnurl").Value);
                }

                // if (current.AvailableAccounts.Any())
                // {
                //     return this.Redirect("/Accounts/Dashboard");
                // }
                return this.Redirect("/Cards/Index");
            }

            AuthenticationManager.Current.SignOut();
            return this.NotFound();
        }
    }
}

digicard.ui/Controllers/ContentController.cs
namespace digicard.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Options;
    using Newtonsoft.Json;
    using digicard.Components;
    using digicard.Components.API;
    using digicard.Components.API.Cards;
    using digicard.Components.Shared.API;
    using digicard.Components.UI.Users;
    using digicard.Components.UI.Authentication;
    using digicard.Mappers;
    using digicard.Models.API.Request.Users;
    using digicard.Models.API.Response.Accounts;
    using digicard.Models.API.Response.Cards;
    using digicard.Components.UI;
    using digicard.Components.UI.Cards;
    using digicard.Models.UI.Page.Authentication;
    using digicard.Models.UI.Page.Content;
//    using digicard.Models.UI.View.Content;

    [AllowAnonymous]
    public class ContentController : DigicardUIController
    {
        public ContentController(IWebHostEnvironment environment, IOptions<AppSettings> appSettings, IServiceProvider serviceProvider)
            : base(environment, appSettings, serviceProvider)
        {
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ContentIndexPageModel model = new ContentIndexPageModel();

            APIResult result = await CardsAPIContext.Current.GetRandomN(3);

            if(result.Success)
            {
                List<CardResponseModel> response = JsonConvert.DeserializeObject<List<CardResponseModel>>(Convert.ToString(result.Data));
                model.Examples = CardsMapper.MapCardResponseModelListToCardViewModelList(response);
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Contact()
        {
            ContentContactPageModel model = new ContentContactPageModel();
            return View(model);
        }
    }
}

digicard.ui/Views/Authentication/FinishPasswordReset.cshtml
@using digicard.Models.UI.Page.Authentication
@model FinishPasswordResetPageModel
@{
    ViewBag.Title = "Set a new Password";
}

<div class="container mt-5">
    <div class="card col-12 col-md-8 col-lg-6 offset-md-2 offset-lg-3">
        <div class="card-header">
            <h2 class="card-title m-0">Please Set Your New Password</h2>
        </div>

        <div class="card-body">
            <div class='row m-0'>
                @await Html.PartialAsync("~/Views/Shared/_Errors.cshtml", Model)
                @await Html.PartialAsync("~/Views/Shared/_Alerts.cshtml", Model)
            </div>

            <form asp-controller="Authentication" asp-action="FinishPasswordReset" method="post" class="mt-3">
                <div class="row">
                    <div class="col-12 col-md-6 mt-3 form-group">
                        <label asp-for="Password">New Password</label>
                        <input type="password" asp-for="Password" class="form-control" />
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                    </div>

                    <div class="col-12 col-md-6 mt-3 form-group mt-3">
                        <label asp-for="ConfirmPassword">Confirm Your Password</label>
                        <input type="password" asp-for="ConfirmPassword" class="form-control" />
                        @Html.ValidationMessageFor(m => m.ConfirmPassword, "", new { @class = "text-danger" })
                    </div>
                </div>
                
                <div class="d-flex flex-column justify-content-end mt-4">
                    <div class="btn-group" role="group" aria-label="Button Group">
                        <a asp-controller="Authentication" asp-action="Login" class="btn btn-secondary w-50">Cancel</a>
                        <button type="submit" asp-controller="Authentication" asp-action="Register" class="btn btn-primary w-50">Set Password</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

digicard.ui/Views/Authentication/Login.cshtml
@using digicard.Models.UI.Page.Authentication
@model LoginPageModel
@{
    ViewBag.Title = "Login";
}

<div class="container mt-5">
    <div class="card col-12 col-md-8 col-lg-6 offset-md-2 offset-lg-3">
        <div class="card-header">
            <h2 class="card-title m-0">Log In</h2>
        </div>

        <div class="card-body">
            <form asp-action="Login" asp-controller="Authentication" asp-method="Post">
                <div class="form-group">
                    <label asp-for="EmailAddress">Email Address</label>
                    <input type="email" asp-for="EmailAddress" class="form-control mb-3" />
                    @Html.ValidationMessageFor(m => m.EmailAddress, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label asp-for="Password">Password</label>
                    <input type="password" asp-for="Password" class="form-control mb-3" />
                    @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                </div>

                <div class="d-flex flex-column justify-content-end mt-4">
                    <div class="btn-group" role="group" aria-label="Button Group">
                        <a asp-controller="Authentication" asp-action="Register" class="btn btn-secondary w-50">Create Account</a>
                        <button type="submit" class="btn btn-primary w-50">Sign In</button>
                    </div>

                    <div class="d-flex justify-content-end mt-3">
                        <a asp-controller="Authentication" asp-action="StartPasswordReset">Forgotten your password?</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

digicard.ui/Views/Authentication/Register.cshtml
@using digicard.Models.UI.Page.Authentication
@model RegisterPageModel

<div class="container mt-5">
    <div class="card col-12 col-md-8 col-lg-6 offset-md-2 offset-lg-3">
        <div class="card-header">
            <h2 class="card-title m-0">Register</h2>
        </div>

        <div class="card-body">
            <div class='row m-0'>
                @await Html.PartialAsync("~/Views/Shared/_Errors.cshtml", Model)
                @await Html.PartialAsync("~/Views/Shared/_Alerts.cshtml", Model)
            </div>

            <form asp-controller="Authentication" asp-action="Register" asp-method="Post">
                <div class="form-group">
                    <label asp-for="EmailAddress">Email Address</label>
                    <input type="email" asp-for="EmailAddress" class="form-control" />
                    @Html.ValidationMessageFor(m => m.EmailAddress, "", new { @class = "text-danger" })
                </div>

                <div class="row">
                    <div class="col-12 col-md-6 mt-3 form-group">
                        <label asp-for="Password">Password</label>
                        <input type="password" asp-for="Password" class="form-control" />
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                    </div>

                    <div class="col-12 col-md-6 mt-3 form-group">
                        <label asp-for="ConfirmPassword">Confirm Password</label>
                        <input type="password" asp-for="ConfirmPassword" class="form-control" />
                        @Html.ValidationMessageFor(m => m.ConfirmPassword, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-row d-flex justify-content-end mt-4">
                </div>

                <div class="d-flex flex-column justify-content-end mt-4">
                    <div class="btn-group" role="group" aria-label="Button Group">
                        <a asp-controller="Content" asp-action="Index" class="btn btn-secondary w-50">Cancel</a>
                        <button type="submit" asp-controller="Authentication" asp-action="Register" class="btn btn-primary w-50">Register</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

digicard.ui/Views/Authentication/StartPasswordReset.cshtml
@using digicard.Models.UI.Page.Authentication
@model StartPasswordResetPageModel
@{ 
    ViewBag.Title = "Password Reset"; 
}

<div class="container mt-5">
    <div class="card col-12 col-md-8 col-lg-6 offset-md-2 offset-lg-3">
        <div class="card-header">
            <h2 class="card-title m-0">Recover Your Password</h2>
        </div>

        <div class="card-body">
            <div class='row m-0'>
                @await Html.PartialAsync("~/Views/Shared/_Errors.cshtml", Model)
                @await Html.PartialAsync("~/Views/Shared/_Alerts.cshtml", Model)
            </div>

            <form asp-controller="Authentication" asp-action="StartPasswordReset" method="post">
                <div class="form-group">
                    <label asp-for="EmailAddress">Email Address</label>
                    <input type="email" asp-for="EmailAddress" class="form-control" />
                    @Html.ValidationMessageFor(m => m.EmailAddress, "", new { @class = "text-danger" })
                </div>

                <div class="d-flex flex-column justify-content-end mt-4">
                    <div class="btn-group" role="group" aria-label="Button Group">
                        <a asp-controller="Authentication" asp-action="Login" class="btn btn-secondary w-50">Cancel</a>
                        <button type="submit" class="btn btn-primary w-50">Start Recovery</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>